#!/bin/bash

BASH_DIR="${DOTFILES}/bash"

source ${BASH_DIR}/_config.sh

cd $DOTFILES

REPOSITORY_URL=$(grep "url = " .git/config | sed "s/.*url = \(.*\)/\1/")

step "Git assume no change"
git update-index --assume-unchanged ${DOTFILES}/.ssh/authorized_keys

step "Checking local changes"
GIT_STATUS=$(git status)

if [[ "$GIT_STATUS" == *"Changes not staged for commit"* ]]; then
  step "Stashing local changes"
  STASH_SAVE=$(git stash save "before_update" >> /dev/null)
fi

step "Pulling latest changes from: ${REPOSITORY_URL}"
$(git pull >> /dev/null)

if [[ "$GIT_STATUS" == *"Changes not staged for commit"* ]]; then
  step "Applying stashed local changes"
  STASH_POP=$(git stash pop $(git stash list | grep "before_update" | sed "s/\(stash\@{\(.*\)}\):\(.*\)/\1/") >> /dev/null)
fi


all_done

reload-terminal
