#!/bin/bash

BASH_DIR="${DOTFILES}/bash"

source ${BASH_DIR}/_config.sh

INSTALL_VERSION="${1}"

old_node_version=$(node --version)
old_yarn_version=$(yarn --version)
old_npm_version=$(npm --version)

step "Versions before"
minor_step "node       : ${old_node_version}"
minor_step "yarn       : ${old_yarn_version}"
minor_step "npm        : ${old_npm_version}"

step "Installing new versions"
nvm install $INSTALL_VERSION --reinstall-packages-from=${old_node_version}
nvm alias default $INSTALL_VERSION
nvm use $INSTALL_VERSION
npm install yarn -g

new_node_version=$(node --version)
new_yarn_version=$(yarn --version)
new_npm_version=$(npm --version)

step "Versions after"
minor_step "node       : ${new_node_version}"
minor_step "yarn       : ${new_yarn_version}"
minor_step "npm        : ${new_npm_version}"

all_done
