#!/bin/bash

BASH_DIR="${DOTFILES}/bash"

source ${BASH_DIR}/_config.sh

COMMANDS="${@:1}"

clear
clear
output_divider "TERMINAL CLEARED"

if [[ "${COMMANDS}" ]]; then
  info "Executing: ${COMMANDS}";

  eval "${COMMANDS}"

  info "Done at: $(date '+%Y-%m-%d %H:%M:%S')"

  all_done
fi
