#!/bin/bash

BASH_DIR="${DOTFILES}/bash"

# shellcheck source=/dev/null
source "${BASH_DIR}/_config.sh"

COMMANDS="${*:1}"

echo -ne "\033c"
output_divider "TERMINAL CLEARED"

if [[ "${COMMANDS}" ]]; then
  info "Executing: ${COMMANDS}";
  
  eval "${COMMANDS}"
  
  info "Done at: $(date '+%Y-%m-%d %H:%M:%S')"
  
  all_done
fi
