#!/bin/bash

BASH_DIR="${DOTFILES}/bash"

source ${BASH_DIR}/_config.sh

KEY_NAME=${1}
KEY_FILE_NAME="${KEY_NAME}.${KEY_EXTENSION}"

KEY_FILE="${DOTFILES}/.ssh/keys/${KEY_FILE_NAME}"
ENABLED_FILE="${DOTFILES}/.ssh/enabled-keys/${KEY_FILE_NAME}"

if [ ! -d "${DOTFILES}/.ssh/enabled-keys/" ]; then
  step "Creating '${DOTFILES}/.ssh/enabled-keys/' folder"
  mkdir -p "${DOTFILES}/.ssh/enabled-keys/"
fi

step "Enabling key '${KEY_FILE_NAME}'"
if [ ! -f ${KEY_FILE} ]; then
  hard_fail "The key '${KEY_FILE_NAME}' does not exist."
fi

if [ -f ${ENABLED_FILE} ]; then
  step_failed "The key '${KEY_FILE_NAME}' has already been enabled."
else
  ln -s ${DOTFILES}/.ssh/keys/${KEY_NAME}.${KEY_EXTENSION} ${DOTFILES}/.ssh/enabled-keys/${KEY_NAME}.${KEY_EXTENSION}
fi

bash ${COMMANDS_DIR}/populate-authorized-keys
