#!/bin/bash

COMMANDS_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
ROOT_DIR=$(dirname "${COMMANDS_DIR}")
BASH_DIR="${ROOT_DIR}/bash"

source ${BASH_DIR}/_config.sh

KEY_NAME=${1}
KEY_FILE_NAME="${KEY_NAME}.remote"

KEY_FILE="${ROOT_DIR}/.ssh/keys/${KEY_FILE_NAME}"
ENABLED_FILE="${ROOT_DIR}/.ssh/enabled-keys/${KEY_FILE_NAME}"

if [ ! -d "${ROOT_DIR}/.ssh/enabled-keys/" ]; then
  step "Creating '${ROOT_DIR}/.ssh/enabled-keys/' folder"
  mkdir -p "${ROOT_DIR}/.ssh/enabled-keys/"
fi

step "Enabling key '${KEY_FILE_NAME}'"
if [ ! -f ${KEY_FILE} ]; then
  hard_fail "The key '${KEY_FILE_NAME}' does not exist."
fi

if [ -f ${ENABLED_FILE} ]; then
  step_failed "The key '${KEY_FILE_NAME}' has already been enabled."
else
  ln -s ${ROOT_DIR}/.ssh/keys/${KEY_NAME}.remote ${ROOT_DIR}/.ssh/enabled-keys/${KEY_NAME}.remote
fi

bash ${COMMANDS_DIR}/populate-authorized-keys
