#!/bin/bash

BASH_DIR="${DOTFILES}/bash"

# shellcheck source=/dev/null
source "${BASH_DIR}/_config.sh"

_cd "${HOME}"

NVM_DIR="${HOME}/.nvm"
export PROFILE="${HOME}/.bash_paths"

mkdir -p "${NVM_DIR}"

step "Downloading nvm"
curl -so- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash

if [ -d "${NVM_DIR}" ]; then
  # shellcheck disable=2016
  if ! command grep -qc '$NVM_DIR/bash_completion' "$PROFILE"; then
    step "Adding nvm bash_completion info ${PROFILE}"
    
    # shellcheck disable=2016
    echo '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion' >> "${PROFILE}"
  fi
  
  # shellcheck source=/dev/null
  source "${NVM_DIR}/nvm.sh"
  
  step "Installing latest node lts"
  nvm install node
  
  step "Installing latest yarn"
  npm install -g yarn
  
  all_done
  
  info "Reload your terminal by running command: reload-terminal"
else
  hard_fail "Folder '${HOME}/.nvm' not found"
fi
