#!/bin/bash

BASH_DIR="${DOTFILES}/bash"

# shellcheck source=/dev/null
source "${BASH_DIR}/_config.sh"

COMMANDS="${*:1}"

LINES=$(${COMMANDS})

echo -e "${LINES}"

echo "Line count: $(echo "${LINES}" | wc -l)"
