#!/bin/bash

COMMANDS_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
DOTFILES=$(cd "$(dirname "${COMMANDS_DIR}")" && pwd)
BASH_DIR="${DOTFILES}/bash"

# shellcheck source=/dev/null
source "${BASH_DIR}/_config.sh"

_cd "${HOME}"

remove_symlink () {
  SYMLINK_TO=${1}
  
  if [[ -L "${SYMLINK_TO}" ]]; then
    minor_step "${SYMLINK_TO}"
    rm "${SYMLINK_TO}" 2> /dev/null
  fi
}

step "Removing symlinks"
for PATH_TO in "${PATHS_TO_PROCESS[@]}"; do
  remove_symlink "${PATH_TO}"
done

step "Re-installing"
"${DOTFILES}/install.sh"
