#!/bin/bash

COMMANDS_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
ROOT_DIR=$(dirname "${COMMANDS_DIR}")
BASH_DIR="${ROOT_DIR}/bash"

source ${BASH_DIR}/_config.sh

cd $ROOT_DIR

REPOSITORY_URL=$(grep "url = " .git/config | sed "s/.*url = \(.*\)/\1/")

step "Ignore all '.local_*' file changes"
git update-index --assume-unchanged .local_*

step "Checking local changes"
GIT_STATUS=$(git status)

if [[ "$GIT_STATUS" == *"Changes not staged for commit"* ]]; then
  step "Stashing local changes"
  STASH_SAVE=$(git stash save "before_update" >> /dev/null)
fi

step "Pulling latest changes from: ${REPOSITORY_URL}"
$(git pull >> /dev/null)

if [[ "$GIT_STATUS" == *"Changes not staged for commit"* ]]; then
  step "Applying stashed local changes"
  STASH_POP=$(git stash pop $(git stash list | grep "before_update" | sed "s/\(stash\@{\(.*\)}\):\(.*\)/\1/") >> /dev/null)
fi


all_done